-- Rename FK constraint names: place_id -> entity_id (references entities.id)
ALTER TABLE public.energy_scores RENAME CONSTRAINT energy_scores_place_id_fkey TO energy_scores_entity_id_fkey;
ALTER TABLE public.gpid_resolution_queue RENAME CONSTRAINT gpid_resolution_queue_place_id_fkey TO gpid_resolution_queue_entity_id_fkey;
ALTER TABLE public.map_places RENAME CONSTRAINT map_places_place_id_fkey TO map_places_entity_id_fkey;
ALTER TABLE public.merchant_enrichment_runs RENAME CONSTRAINT merchant_enrichment_runs_place_id_fkey TO merchant_enrichment_runs_entity_id_fkey;
ALTER TABLE public.merchant_signals RENAME CONSTRAINT merchant_signals_place_id_fkey TO merchant_signals_entity_id_fkey;
ALTER TABLE public.operator_place_candidates RENAME CONSTRAINT operator_place_candidates_place_id_fkey TO operator_place_candidates_entity_id_fkey;
ALTER TABLE public.person_places RENAME CONSTRAINT person_places_place_id_fkey TO person_places_entity_id_fkey;
ALTER TABLE public.place_actor_relationships RENAME CONSTRAINT place_actor_relationships_place_id_fkey TO place_actor_relationships_entity_id_fkey;
ALTER TABLE public.place_appearances RENAME CONSTRAINT place_appearances_host_place_id_fkey TO place_appearances_host_entity_id_fkey;
ALTER TABLE public.place_appearances RENAME CONSTRAINT place_appearances_subject_place_id_fkey TO place_appearances_subject_entity_id_fkey;
ALTER TABLE public.place_coverage_status RENAME CONSTRAINT place_coverage_status_place_id_fkey TO place_coverage_status_entity_id_fkey;
ALTER TABLE public.place_photo_eval RENAME CONSTRAINT place_photo_eval_place_id_fkey TO place_photo_eval_entity_id_fkey;
ALTER TABLE public.place_tag_scores RENAME CONSTRAINT place_tag_scores_place_id_fkey TO place_tag_scores_entity_id_fkey;
ALTER TABLE public.viewer_bookmarks RENAME CONSTRAINT viewer_bookmarks_place_id_fkey TO viewer_bookmarks_entity_id_fkey;
export DB_ENV=local