-- DB-only migration — restored locally 2026-03-09.
-- RETIRED: no executable DDL.
--
-- This migration was intended to rename place_id → entity_id in proposed_signals
-- and operational_overlays, mirroring the places → entities rename (20260228100000).
--
-- The target tables (proposed_signals, operational_overlays) are confirmed absent
-- from the live DB. The migration's effect is therefore moot regardless of whether
-- the rename ran before or after the tables were dropped.
--
-- The local schema still models both tables with @map("place_id"), consistent
-- with the rename never persisting to the live schema.
--
-- DO NOT re-apply. Register with:
--   npx prisma migrate resolve --applied 20260301000000_rename_place_id_to_entity_id_signals_overlays
